# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.provision :file, source: "vagrant/run-radar.cron", destination: "/tmp/run-radar"
  config.vm.provision :shell, path: "vagrant/bootstrap.sh"
end
